config/routes.rb
Rails.application.routes.draw do
  devise_for :users

resources :graphs

root 'graphs#index'

end

app/models/graph.rb
class Graph < ActiveRecord::Base

belongs_to :user


def difference
	if sales != nil
	1-(sales_goal-sales)-1
		else
    puts "?"
end
end

def ratio
	if sales != nil
	(sales/sales_goal)*100
	else
    puts "?"
end
end


end

app/models/user.rb
class User < ActiveRecord::Base

has_many :graphs

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

def index
	@graphs = Graph.all.order("id DESC").all
	@charts = Graph.all
end

def new
	@graph = Graph.new
end

def create
	@graph = Graph.new(graph_params)	
	if @graph.save
	redirect_to @graph
	else
	render 'new'
end
end

def show
	@graph = Graph.find(params[:id])
end

def edit
	@graph = Graph.find(params[:id])
end

def update
	@graph = Graph.find(params[:id])
	graph_params = params.require(:graph).			   
	permit(:title, :sales, :sales_goal)
	@graph.update(graph_params)
	redirect_to @graph
end

def destroy
	@graph = Graph.find(params[:id])
	@graph.destroy
	redirect_to root_path
end

private
def graph_params
	params.require(:graph).
	permit(:title, :sales, :sales_goal)
 end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def homepage
end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/graphs_helper.rb
module GraphsHelper

def sales_success(graph)
if graph.sales == nil
	puts 
"Please enter your sales. Without the numbers, we just feel lost inside."
else

if graph.sales < 10000
"It was a bad week, but you'll do better next time"

else
if graph.sales > 20000
"Wow, this week went mind-blowingly good, you sales machine, you!"

else
"Meh, this week was decent but you can do better."	
end
end	
end
end


def graph_status(sales)
if sales != nil
    return 'none'
else
	return 'overdue'
end
end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/graphs/_form.html.erb
<%= form_for(@graph) do |f| %>
<p class="label label-primary">Week Name</p><br>
<%= f.text_field :title %>
</p>
<p class="label label-primary">Sales Goal</p><br>
<%= f.number_field :sales_goal %>	
</p>
<p class="label label-primary">Sales</p><br>
<%= f.number_field :sales %>	
</p>
<p>
<%= f.submit "Save", class: "btn btn-small btn-info" %>
</p>
<% end %>

app/views/graphs/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <div class="jumbotron-contents">
        <h1>Update This Week's Sales!</h1>
        <p>
        	<%= render 'form' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/graphs/index.html.erb
<div class="row">
  <div class="col-md-12">
     <% if user_signed_in? %>
    <div class="row">
      <div class="col-md-8" id="left">
        <div class="jumbotron">
          <div class="jumbotron-contents">
            <h1>Your Total Sales</h1>
            <p>
            <div id="highChartContainer" style="min-width: 450px; height: 450px; margin: 0 auto"></div>

            </p>
          </div>
        </div>
      </div>

      <div class="col-md-4" id="right">
        <div class="jumbotron">
          <div class="jumbotron-contents">
              <%= link_to "Add New Sales", new_graph_path, class: "btn btn-small btn-rounded" %><br>
              <h1>Past Weekly Sales Stats</h1>
              <p>
                <% @graphs.each do |graph| %>
                <div class="container">
                  <h3><strong><%= graph.title %></strong></h3>
                  <i>Submitted On:</i>
                  <%= (graph.created_at) %>
                  <br><br>
                  <strong>Sales Goal:</strong>
                  <%= number_to_currency(graph.sales_goal) %>
                  <br>
                  <span class="<%= graph_status(graph.sales) %>">
                  <strong>Actual Sales:</strong>
                  <%= number_to_currency(graph.sales) %>
                  <br>
                  <strong>Difference:</strong>    
                  <%= number_to_currency(graph.difference) %>
                  <br>
                  <strong>Closing Ratio:</strong>    
                  <%= number_to_percentage(graph.ratio, precision: 0) %>    
                  <br><br>
                  <b>How You Did:</b>
                  <%= sales_success(graph) %> 
                  <br>
                  <%= link_to "See More", graph_path(graph) %>            
                  <hr></span>                 
                  <% end %>  
                </p>
            </div>
          </div>
        </div>    

        </div>
      </div>
    </div>
 


         <% else %>
          <%= render 'layouts/home' %>
  </div>
</div>   
<% end %>



<script type='text/javascript'>
    chart = new Highcharts.Chart({
    chart: {
        renderTo: 'highChartContainer',
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false
    },
    xAxis: {
    title: { text: 'Week' },
    },

    yAxis: {
    title: { text: 'Dollars' },
    },

    title: {
        text: ''
    },
    series: [{
      name: "Sales",
      type: 'line',     
      data: <%= @charts.map do |chart|
    [chart.sales.to_f]
    end.to_json.html_safe %>
    },
    {
      name: "Goal",
      type: 'line',     
      data: <%= @charts.map do |chart|
    [chart.sales_goal.to_f]
    end.to_json.html_safe %>
    }]
  });
</script>

app/views/graphs/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <div class="jumbotron-contents">
        <h1>Add This Week's Sales!</h1>
        <p>
        	<%= render 'form' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/graphs/show.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="jumbotron">
      	<div class="jumbotron-contents">
      		<div class="row">
	      		<div class="col-md-12">
		          <h1><strong><%= @graph.title %> Sales</strong></h1>
		          <h2>
		          <div class="label label-primary">Sales Goal:&nbsp&nbsp&nbsp&nbsp&nbsp</div>
		          <%= number_to_currency(@graph.sales_goal) %><br><br>
		          <div class="label label-primary">Actual Sales:&nbsp&nbsp</div>
		          <%= number_to_currency(@graph.sales) %><br><br>
		          <div class="label label-primary">Difference:&nbsp&nbsp&nbsp&nbsp&nbsp</div>
		           <%= number_to_currency(@graph.difference) %><br><br>
		          <div class="label label-primary">Closing Ratio:</div>
		          <%= number_to_percentage(@graph.ratio, precision: 2) %><br><br>  
		          </h2> 
		         <hr>
                <b>How You Did:</b>
                <span class="<%= graph_status(@graph.sales) %>">
                <%= sales_success(@graph) %> 
            	</span>
                <br>
                <hr>     
		          <br>
		          <%= link_to "Edit", edit_graph_path, class: "btn btn-small btn-info" %>
		          <%= link_to "Delete", graph_path(@graph), class: "btn btn-small btn-danger", 
		          method: :delete, data: {confirm: 'Are you sure?'} %>	
				  <%= link_to "Back to Main", root_path, class: "btn btn-small btn-primary pull-right" %>            
		        </div>  
	     	</div>
	    </div>
	</div>
  </div>	

  <div class="col-md-7">
    <div class="jumbotron">
      <div class="jumbotron-contents graph">
          <h1><strong>Your Sales Performance</h1>
            <div id="showhighChartContainer" style="min-width: 350px; height: 350px; margin: 0 auto"></div>

          <br>
          <br>
          <br>
          <br>   
      </div>
    </div>
  </div>

</div>


<script type='text/javascript'>
  new Highcharts.Chart({
    chart: { renderTo: 'showhighChartContainer' },
    title: { text: 'Sales Against Goal' },
    xAxis: { type: 'name' },

    yAxis: {
      title: { text: 'Dollars' }
    },

    series: [{
      name: "Sales",
      type: 'column',    	
      data: <%= [@graph.sales_goal.to_f] %>
    },
    {
      name: "Goal",
      type: 'column',    	
      data: <%= [@graph.sales.to_f] %>
    }]    
  });

</script>

app/views/layouts/_header.html.erb
<div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to "Overview", root_path %></li>
                <li><%= link_to "Add Weekly Sales", new_graph_path %>
                <!-- <li class="disabled"><a href="#">Link</a></li> -->

              </ul>
              <div class="collapse navbar-collapse navbar-right" role="">
              <ul class="nav navbar-nav">

              <% if user_signed_in? %>
              <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                          <ul class="dropdown-menu" role="menu">
                            <li class="inactive"><%= link_to "Settings", edit_user_registration_path %></li>
                            <li class="inactive"><li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                          </ul>
                        </li>                             
                   <% end %>                     
                  </ul>
                </li>
              </ul>                      
            </div>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </div>
    </div>

app/views/layouts/_home.html.erb
    <div class="row">
             <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
             <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>      
     </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Graphs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag "highcharts" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= csrf_meta_tags %>
</head>
<body>

<body style="background-color: rgb(241, 242, 246);">

<% if user_signed_in? %>
<%= render 'layouts/header' %>
<% end %>

<%= yield %>
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

</body>

</body>
</html>

app/views/welcome/homepage.html.erb
<body>
<div id="headerSection">
	<div class="container">
		
	    <div class="span3 logo">
	    <%= image_tag 'homepage/logo1.png' %>
		</div>
		
		<div class="navbar">
			<button class="pull-right ddbtn" id="toggle-btn"><%= image_tag 'homepage/drop-down.png' %></button>
            <div id="menu" class="nav-collapse">
				<ul class="nav mynav">
					<li><a href="#meetourteamSection">Features</a></li>
					<li><a href="#contactSection">Contact</a></li>
            <li><a href="/users/sign_in">Login</a></li>
				</ul>
			</div>
			
		</div>
	</div>
</div>	
<!--Header Ends================================================ -->

<div id="carouselSection" class="cntr"> 
		<div id="myCarousel" class="carousel slide">
		
			<div class="carousel-inner">
				<div class="item active">
					<a class="cntr" href="#"><%= image_tag 'homepage/1.png' %> 
				</div>
				
				<div class="item">
					<a class="cntr" href="#"><%= image_tag 'homepage/1.png' %> 
				</div>
				
				
			</div>
			<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>
</div>

<!-- Sectionone block ends======================================== -->

<!-- Our Services======================================== -->
<div id="ourServices"> 	
<div class="container">	
				<div class="row">
                
      <div class="col-md-4 col-xs-12">
      
      <div class="info-img">
        <%= image_tag 'homepage/img-1.png' %> </div>
        <h4>Flat Design</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et quam est. Mauris faucibus tellus ac auctor posuere. </p>
      </div>
      <div class="col-md-4 col-xs-12">
        <div class="info-img"><%= image_tag 'homepage/img-2.png' %> </div>
        <h4>Great Ideas</h4>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et quam est. Mauris faucibus tellus ac auctor posuere. </p>
      </div>
      <div class="col-md-4 col-xs-12">
        <div class="info-img"><%= image_tag 'homepage/img-3.png' %> </div>
        <h4>Browser  Compatibility</h4>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et quam est. Mauris faucibus tellus ac auctor posuere. </p>
      </div>
    </div>
</div>
</div>
</div>


<!-- Meet our team======================================== -->
<div id="meetourteamSection">
<div class="col-xs-12"><h1 class="cntr">FEATURES</h1>
<p style="color:white;">
• Book More Brides By Measuring Your Progress!<br><br>
• Track Sales, Leads and Goals<br><br>
• Visualize Performance With Graphs<br><br>
• Ensure You Are Staying On Track

</p></div>
<div class="container">	
	
<div class="tabbable tabs">
<div class="tab-content label-primary">

	<div class="tab-pane active" id="all">
	<ul class="thumbnails">
	
		<li class="col-sm-12 col-xs-12">
		</li>
		
			
	</ul>
      <a href="#" class="btn btn-large btn-primary" style="color: #a2a3a3;background-color: #fff;">SHOW MORE</a>

    
	</div>
	
	
	
	

	
	
</div>
</div>
</div>
</div>


<!-- Contact Section -->
<div id="contactSection">
<div class="col-xs-12"><h1 class="cntr">Contact Us</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et quam est. Mauris faucibus tellus ac auctor posuere. </p></div>
	<div class="container">	
		<div class="row form-cover">	
		<div class="col-xs-12 ">
			
			<form class="form-horizontal">
				<fieldset>
				  <div class="control-group">
					
					<div class="controls">
					  <input type="text" class="input-xlarge" id="input01" >
					 
					</div>
				  </div>
				   <div class="control-group">
					
					<div class="controls">
					  <input type="text" class="input-xlarge" id="input11">
					 
					</div>
				  </div>
				   <div class="control-group">
					
					<div class="controls">
					  <textarea class="input-xlarge" id="textarea" rows="3" style="height:210px"></textarea>
					</div>
				  </div>
				  
				 
					<button type="submit" class="btn btn-large btn-primary" style="color: #a2a3a3;background-color: #fff;margin-top:30px;">Send Message</button>
					
				</fieldset>
			  </form>
		</div> 
		
		
		</div> 
		</div> 
        
     <div class="footerSection container">
	
       
                <div class=" col-sm-6 socialicon">
                    <a class="facebook" href="http://www.facebook.com/xtendify"></a>
                    <a class="twitter" href="http://www.twitter.com/xtendify"></a>
                    <a class="html5" href="#"></a>
                    <a class="icon2" href="#"></a>
                </div>
                
        
	
		<div class="copyright"><p>  Copyright 2016 | Developed By <a href="http://www.eventtemple.com">Event Temple</a></p></div>
		<!--To remove this copyright notice, please donate via Xtendify at - https://www.xtendify.com/en/product/103-colorful-flat-bootstrap-theme. It will support the development process -->
		
	</div>

        
        
        
</div> 

<!-- Wrapper end -->


<a href="#" class="go-top" ><i class="glyphicon glyphicon-arrow-up"></i></a>


<script src="js/jquery-1.9.1.min.js"></script>
<script src="js/bootstrap.min.js" type="text/javascript"></script>
<script src="js/jquery.scrollTo-1.4.3.1-min.js" type="text/javascript"></script>
<script src="js/jquery.easing-1.3.min.js"></script>
<script src="js/default.js"></script>
<script src="js/my_js.js"></script>
<script type="text/javascript">

	$(document).ready(function() {
	$('#myCarousel').carousel({
	  interval: 7000
	});
    $('#toggle-btn').click(function(){
		$('#menu').toggle("fast");
	});
	
	});
</script>
<style>
</style>
</body>
</html>